# Generated by Django 3.1.14 on 2023-08-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230823_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportStatus',
            fields=[
                ('report_id', models.TextField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
